# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/akaseb/hussein/test_ci

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/akaseb/hussein/test_ci

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/akaseb/hussein/test_ci/CMakeFiles /home/akaseb/hussein/test_ci/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/akaseb/hussein/test_ci/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Benchmark

# Build rule for target.
Benchmark: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Benchmark
.PHONY : Benchmark

# fast build rule for target.
Benchmark/fast:
	$(MAKE) -f CMakeFiles/Benchmark.dir/build.make CMakeFiles/Benchmark.dir/build
.PHONY : Benchmark/fast

Benchmark.o: Benchmark.cxx.o

.PHONY : Benchmark.o

# target to build an object file
Benchmark.cxx.o:
	$(MAKE) -f CMakeFiles/Benchmark.dir/build.make CMakeFiles/Benchmark.dir/Benchmark.cxx.o
.PHONY : Benchmark.cxx.o

Benchmark.i: Benchmark.cxx.i

.PHONY : Benchmark.i

# target to preprocess a source file
Benchmark.cxx.i:
	$(MAKE) -f CMakeFiles/Benchmark.dir/build.make CMakeFiles/Benchmark.dir/Benchmark.cxx.i
.PHONY : Benchmark.cxx.i

Benchmark.s: Benchmark.cxx.s

.PHONY : Benchmark.s

# target to generate assembly for a file
Benchmark.cxx.s:
	$(MAKE) -f CMakeFiles/Benchmark.dir/build.make CMakeFiles/Benchmark.dir/Benchmark.cxx.s
.PHONY : Benchmark.cxx.s

BenchmarkPubSubTypes.o: BenchmarkPubSubTypes.cxx.o

.PHONY : BenchmarkPubSubTypes.o

# target to build an object file
BenchmarkPubSubTypes.cxx.o:
	$(MAKE) -f CMakeFiles/Benchmark.dir/build.make CMakeFiles/Benchmark.dir/BenchmarkPubSubTypes.cxx.o
.PHONY : BenchmarkPubSubTypes.cxx.o

BenchmarkPubSubTypes.i: BenchmarkPubSubTypes.cxx.i

.PHONY : BenchmarkPubSubTypes.i

# target to preprocess a source file
BenchmarkPubSubTypes.cxx.i:
	$(MAKE) -f CMakeFiles/Benchmark.dir/build.make CMakeFiles/Benchmark.dir/BenchmarkPubSubTypes.cxx.i
.PHONY : BenchmarkPubSubTypes.cxx.i

BenchmarkPubSubTypes.s: BenchmarkPubSubTypes.cxx.s

.PHONY : BenchmarkPubSubTypes.s

# target to generate assembly for a file
BenchmarkPubSubTypes.cxx.s:
	$(MAKE) -f CMakeFiles/Benchmark.dir/build.make CMakeFiles/Benchmark.dir/BenchmarkPubSubTypes.cxx.s
.PHONY : BenchmarkPubSubTypes.cxx.s

BenchmarkPublisher.o: BenchmarkPublisher.cpp.o

.PHONY : BenchmarkPublisher.o

# target to build an object file
BenchmarkPublisher.cpp.o:
	$(MAKE) -f CMakeFiles/Benchmark.dir/build.make CMakeFiles/Benchmark.dir/BenchmarkPublisher.cpp.o
.PHONY : BenchmarkPublisher.cpp.o

BenchmarkPublisher.i: BenchmarkPublisher.cpp.i

.PHONY : BenchmarkPublisher.i

# target to preprocess a source file
BenchmarkPublisher.cpp.i:
	$(MAKE) -f CMakeFiles/Benchmark.dir/build.make CMakeFiles/Benchmark.dir/BenchmarkPublisher.cpp.i
.PHONY : BenchmarkPublisher.cpp.i

BenchmarkPublisher.s: BenchmarkPublisher.cpp.s

.PHONY : BenchmarkPublisher.s

# target to generate assembly for a file
BenchmarkPublisher.cpp.s:
	$(MAKE) -f CMakeFiles/Benchmark.dir/build.make CMakeFiles/Benchmark.dir/BenchmarkPublisher.cpp.s
.PHONY : BenchmarkPublisher.cpp.s

BenchmarkSubscriber.o: BenchmarkSubscriber.cpp.o

.PHONY : BenchmarkSubscriber.o

# target to build an object file
BenchmarkSubscriber.cpp.o:
	$(MAKE) -f CMakeFiles/Benchmark.dir/build.make CMakeFiles/Benchmark.dir/BenchmarkSubscriber.cpp.o
.PHONY : BenchmarkSubscriber.cpp.o

BenchmarkSubscriber.i: BenchmarkSubscriber.cpp.i

.PHONY : BenchmarkSubscriber.i

# target to preprocess a source file
BenchmarkSubscriber.cpp.i:
	$(MAKE) -f CMakeFiles/Benchmark.dir/build.make CMakeFiles/Benchmark.dir/BenchmarkSubscriber.cpp.i
.PHONY : BenchmarkSubscriber.cpp.i

BenchmarkSubscriber.s: BenchmarkSubscriber.cpp.s

.PHONY : BenchmarkSubscriber.s

# target to generate assembly for a file
BenchmarkSubscriber.cpp.s:
	$(MAKE) -f CMakeFiles/Benchmark.dir/build.make CMakeFiles/Benchmark.dir/BenchmarkSubscriber.cpp.s
.PHONY : BenchmarkSubscriber.cpp.s

Benchmark_big.o: Benchmark_big.cxx.o

.PHONY : Benchmark_big.o

# target to build an object file
Benchmark_big.cxx.o:
	$(MAKE) -f CMakeFiles/Benchmark.dir/build.make CMakeFiles/Benchmark.dir/Benchmark_big.cxx.o
.PHONY : Benchmark_big.cxx.o

Benchmark_big.i: Benchmark_big.cxx.i

.PHONY : Benchmark_big.i

# target to preprocess a source file
Benchmark_big.cxx.i:
	$(MAKE) -f CMakeFiles/Benchmark.dir/build.make CMakeFiles/Benchmark.dir/Benchmark_big.cxx.i
.PHONY : Benchmark_big.cxx.i

Benchmark_big.s: Benchmark_big.cxx.s

.PHONY : Benchmark_big.s

# target to generate assembly for a file
Benchmark_big.cxx.s:
	$(MAKE) -f CMakeFiles/Benchmark.dir/build.make CMakeFiles/Benchmark.dir/Benchmark_big.cxx.s
.PHONY : Benchmark_big.cxx.s

Benchmark_bigPubSubTypes.o: Benchmark_bigPubSubTypes.cxx.o

.PHONY : Benchmark_bigPubSubTypes.o

# target to build an object file
Benchmark_bigPubSubTypes.cxx.o:
	$(MAKE) -f CMakeFiles/Benchmark.dir/build.make CMakeFiles/Benchmark.dir/Benchmark_bigPubSubTypes.cxx.o
.PHONY : Benchmark_bigPubSubTypes.cxx.o

Benchmark_bigPubSubTypes.i: Benchmark_bigPubSubTypes.cxx.i

.PHONY : Benchmark_bigPubSubTypes.i

# target to preprocess a source file
Benchmark_bigPubSubTypes.cxx.i:
	$(MAKE) -f CMakeFiles/Benchmark.dir/build.make CMakeFiles/Benchmark.dir/Benchmark_bigPubSubTypes.cxx.i
.PHONY : Benchmark_bigPubSubTypes.cxx.i

Benchmark_bigPubSubTypes.s: Benchmark_bigPubSubTypes.cxx.s

.PHONY : Benchmark_bigPubSubTypes.s

# target to generate assembly for a file
Benchmark_bigPubSubTypes.cxx.s:
	$(MAKE) -f CMakeFiles/Benchmark.dir/build.make CMakeFiles/Benchmark.dir/Benchmark_bigPubSubTypes.cxx.s
.PHONY : Benchmark_bigPubSubTypes.cxx.s

Benchmark_main.o: Benchmark_main.cpp.o

.PHONY : Benchmark_main.o

# target to build an object file
Benchmark_main.cpp.o:
	$(MAKE) -f CMakeFiles/Benchmark.dir/build.make CMakeFiles/Benchmark.dir/Benchmark_main.cpp.o
.PHONY : Benchmark_main.cpp.o

Benchmark_main.i: Benchmark_main.cpp.i

.PHONY : Benchmark_main.i

# target to preprocess a source file
Benchmark_main.cpp.i:
	$(MAKE) -f CMakeFiles/Benchmark.dir/build.make CMakeFiles/Benchmark.dir/Benchmark_main.cpp.i
.PHONY : Benchmark_main.cpp.i

Benchmark_main.s: Benchmark_main.cpp.s

.PHONY : Benchmark_main.s

# target to generate assembly for a file
Benchmark_main.cpp.s:
	$(MAKE) -f CMakeFiles/Benchmark.dir/build.make CMakeFiles/Benchmark.dir/Benchmark_main.cpp.s
.PHONY : Benchmark_main.cpp.s

Benchmark_medium.o: Benchmark_medium.cxx.o

.PHONY : Benchmark_medium.o

# target to build an object file
Benchmark_medium.cxx.o:
	$(MAKE) -f CMakeFiles/Benchmark.dir/build.make CMakeFiles/Benchmark.dir/Benchmark_medium.cxx.o
.PHONY : Benchmark_medium.cxx.o

Benchmark_medium.i: Benchmark_medium.cxx.i

.PHONY : Benchmark_medium.i

# target to preprocess a source file
Benchmark_medium.cxx.i:
	$(MAKE) -f CMakeFiles/Benchmark.dir/build.make CMakeFiles/Benchmark.dir/Benchmark_medium.cxx.i
.PHONY : Benchmark_medium.cxx.i

Benchmark_medium.s: Benchmark_medium.cxx.s

.PHONY : Benchmark_medium.s

# target to generate assembly for a file
Benchmark_medium.cxx.s:
	$(MAKE) -f CMakeFiles/Benchmark.dir/build.make CMakeFiles/Benchmark.dir/Benchmark_medium.cxx.s
.PHONY : Benchmark_medium.cxx.s

Benchmark_mediumPubSubTypes.o: Benchmark_mediumPubSubTypes.cxx.o

.PHONY : Benchmark_mediumPubSubTypes.o

# target to build an object file
Benchmark_mediumPubSubTypes.cxx.o:
	$(MAKE) -f CMakeFiles/Benchmark.dir/build.make CMakeFiles/Benchmark.dir/Benchmark_mediumPubSubTypes.cxx.o
.PHONY : Benchmark_mediumPubSubTypes.cxx.o

Benchmark_mediumPubSubTypes.i: Benchmark_mediumPubSubTypes.cxx.i

.PHONY : Benchmark_mediumPubSubTypes.i

# target to preprocess a source file
Benchmark_mediumPubSubTypes.cxx.i:
	$(MAKE) -f CMakeFiles/Benchmark.dir/build.make CMakeFiles/Benchmark.dir/Benchmark_mediumPubSubTypes.cxx.i
.PHONY : Benchmark_mediumPubSubTypes.cxx.i

Benchmark_mediumPubSubTypes.s: Benchmark_mediumPubSubTypes.cxx.s

.PHONY : Benchmark_mediumPubSubTypes.s

# target to generate assembly for a file
Benchmark_mediumPubSubTypes.cxx.s:
	$(MAKE) -f CMakeFiles/Benchmark.dir/build.make CMakeFiles/Benchmark.dir/Benchmark_mediumPubSubTypes.cxx.s
.PHONY : Benchmark_mediumPubSubTypes.cxx.s

Benchmark_small.o: Benchmark_small.cxx.o

.PHONY : Benchmark_small.o

# target to build an object file
Benchmark_small.cxx.o:
	$(MAKE) -f CMakeFiles/Benchmark.dir/build.make CMakeFiles/Benchmark.dir/Benchmark_small.cxx.o
.PHONY : Benchmark_small.cxx.o

Benchmark_small.i: Benchmark_small.cxx.i

.PHONY : Benchmark_small.i

# target to preprocess a source file
Benchmark_small.cxx.i:
	$(MAKE) -f CMakeFiles/Benchmark.dir/build.make CMakeFiles/Benchmark.dir/Benchmark_small.cxx.i
.PHONY : Benchmark_small.cxx.i

Benchmark_small.s: Benchmark_small.cxx.s

.PHONY : Benchmark_small.s

# target to generate assembly for a file
Benchmark_small.cxx.s:
	$(MAKE) -f CMakeFiles/Benchmark.dir/build.make CMakeFiles/Benchmark.dir/Benchmark_small.cxx.s
.PHONY : Benchmark_small.cxx.s

Benchmark_smallPubSubTypes.o: Benchmark_smallPubSubTypes.cxx.o

.PHONY : Benchmark_smallPubSubTypes.o

# target to build an object file
Benchmark_smallPubSubTypes.cxx.o:
	$(MAKE) -f CMakeFiles/Benchmark.dir/build.make CMakeFiles/Benchmark.dir/Benchmark_smallPubSubTypes.cxx.o
.PHONY : Benchmark_smallPubSubTypes.cxx.o

Benchmark_smallPubSubTypes.i: Benchmark_smallPubSubTypes.cxx.i

.PHONY : Benchmark_smallPubSubTypes.i

# target to preprocess a source file
Benchmark_smallPubSubTypes.cxx.i:
	$(MAKE) -f CMakeFiles/Benchmark.dir/build.make CMakeFiles/Benchmark.dir/Benchmark_smallPubSubTypes.cxx.i
.PHONY : Benchmark_smallPubSubTypes.cxx.i

Benchmark_smallPubSubTypes.s: Benchmark_smallPubSubTypes.cxx.s

.PHONY : Benchmark_smallPubSubTypes.s

# target to generate assembly for a file
Benchmark_smallPubSubTypes.cxx.s:
	$(MAKE) -f CMakeFiles/Benchmark.dir/build.make CMakeFiles/Benchmark.dir/Benchmark_smallPubSubTypes.cxx.s
.PHONY : Benchmark_smallPubSubTypes.cxx.s

DynamicTypesHelper.o: DynamicTypesHelper.cpp.o

.PHONY : DynamicTypesHelper.o

# target to build an object file
DynamicTypesHelper.cpp.o:
	$(MAKE) -f CMakeFiles/Benchmark.dir/build.make CMakeFiles/Benchmark.dir/DynamicTypesHelper.cpp.o
.PHONY : DynamicTypesHelper.cpp.o

DynamicTypesHelper.i: DynamicTypesHelper.cpp.i

.PHONY : DynamicTypesHelper.i

# target to preprocess a source file
DynamicTypesHelper.cpp.i:
	$(MAKE) -f CMakeFiles/Benchmark.dir/build.make CMakeFiles/Benchmark.dir/DynamicTypesHelper.cpp.i
.PHONY : DynamicTypesHelper.cpp.i

DynamicTypesHelper.s: DynamicTypesHelper.cpp.s

.PHONY : DynamicTypesHelper.s

# target to generate assembly for a file
DynamicTypesHelper.cpp.s:
	$(MAKE) -f CMakeFiles/Benchmark.dir/build.make CMakeFiles/Benchmark.dir/DynamicTypesHelper.cpp.s
.PHONY : DynamicTypesHelper.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... Benchmark"
	@echo "... install"
	@echo "... Benchmark.o"
	@echo "... Benchmark.i"
	@echo "... Benchmark.s"
	@echo "... BenchmarkPubSubTypes.o"
	@echo "... BenchmarkPubSubTypes.i"
	@echo "... BenchmarkPubSubTypes.s"
	@echo "... BenchmarkPublisher.o"
	@echo "... BenchmarkPublisher.i"
	@echo "... BenchmarkPublisher.s"
	@echo "... BenchmarkSubscriber.o"
	@echo "... BenchmarkSubscriber.i"
	@echo "... BenchmarkSubscriber.s"
	@echo "... Benchmark_big.o"
	@echo "... Benchmark_big.i"
	@echo "... Benchmark_big.s"
	@echo "... Benchmark_bigPubSubTypes.o"
	@echo "... Benchmark_bigPubSubTypes.i"
	@echo "... Benchmark_bigPubSubTypes.s"
	@echo "... Benchmark_main.o"
	@echo "... Benchmark_main.i"
	@echo "... Benchmark_main.s"
	@echo "... Benchmark_medium.o"
	@echo "... Benchmark_medium.i"
	@echo "... Benchmark_medium.s"
	@echo "... Benchmark_mediumPubSubTypes.o"
	@echo "... Benchmark_mediumPubSubTypes.i"
	@echo "... Benchmark_mediumPubSubTypes.s"
	@echo "... Benchmark_small.o"
	@echo "... Benchmark_small.i"
	@echo "... Benchmark_small.s"
	@echo "... Benchmark_smallPubSubTypes.o"
	@echo "... Benchmark_smallPubSubTypes.i"
	@echo "... Benchmark_smallPubSubTypes.s"
	@echo "... DynamicTypesHelper.o"
	@echo "... DynamicTypesHelper.i"
	@echo "... DynamicTypesHelper.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

